language: ruby
rvm:
  - 3.0.0
before_script:
  - rm -rf public
script:
  - ./script/cibuild.sh
branches:
  only: main
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
cache: bundler
notifications:
  email: false
